export type Ficsmas =
  | 'ficsmas-gift'
  | 'candy-cane'
  | 'ficsmas-actual-snow'
  | 'red-ficsmas-ornament'
  | 'blue-ficsmas-ornament'
  | 'copper-ficsmas-ornament'
  | 'iron-ficsmas-ornament'
  | 'ficsmas-ornament-bundle'
  | 'ficsmas-bow'
  | 'ficsmas-tree-barnch'
  | 'ficsmas-wonder-star'
  | 'ficsmas-wreath'
  | 'snowball'
  | 'sweet-fireworks'
  | 'fancy-fireworks'
  | 'sparkly-fireworks';
